### ISSUE TITLE
Extension prevents build

### ISSUE THREAD

**Issue by ArtFlag** [scopatz/hiddencode#4]
Hi and thanks for the extension.

I noticed 2 problems with the extension and I'm not sure how to fix them.

## Info
- macOS: mojave
- Sphinx: 1.7.9
- Python: 3.7.3
- Building with: `sphinx-build -b html demo_docs/source output`

## First problem
Running the extension to build the HTML output leads to: 

```console
Exception occurred:
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/writers/text.py", line 1196, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: hidden_code_block
```

Full traceback:

```console
Traceback (most recent call last):
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/application.py", line 325, in build
    self.builder.build_all()
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_all
    self.build(None, summary='all source files', method='all')
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 403, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 440, in write
    self._write_serial(sorted(docnames))
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 449, in _write_serial
    self.write_doc(docname, doctree)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/text.py", line 80, in write_doc
    self.writer.write(doctree, destination)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/writers/text.py", line 165, in translate
    self.document.walkabout(visitor)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/writers/text.py", line 1196, in unknown_visit
```

I had this problem with an extension in the past and I fixed it by providing all the args for `app.add_node`:

```python
 app.add_node(hidden_code_block,
        html=(visit_hcb_html, depart_hcb_html),
    )
```
becomes:

```python
def setup(app):
    app.add_directive('hidden-code-block', HiddenCodeBlock)
    app.add_node(hidden_code_block,
        html=(visit_hcb_html, depart_hcb_html),
        latex=(visit_hcb_html, depart_hcb_html),
        text=(visit_hcb_html, depart_hcb_html),
        man=(visit_hcb_html, depart_hcb_html),
        texinfo=(visit_hcb_html, depart_hcb_html),
    )
```

## Second problem

After this fix (is it a fix?), I go one step further:

```console
Exception occurred:
  File "/Users/artflag/repositories/sphinx-theme/demo_docs/source/_ext/hidden_code_blocks.py", line 81, in visit_hcb_html
    code_block = self.body[-1]
AttributeError: 'TextTranslator' object has no attribute 'body'
```

Full traceback:

```console
Traceback (most recent call last):
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/application.py", line 325, in build
    self.builder.build_all()
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_all
    self.build(None, summary='all source files', method='all')
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 403, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 440, in write
    self._write_serial(sorted(docnames))
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 449, in _write_serial
    self.write_doc(docname, doctree)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/builders/text.py", line 80, in write_doc
    self.writer.write(doctree, destination)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/sphinx/writers/text.py", line 165, in translate
    self.document.walkabout(visitor)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/artflag/.local/share/virtualenvs/sphinx-theme-I1JNWXam/lib/python3.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/Users/artflag/repositories/sphinx-theme/demo_docs/source/_ext/hidden_code_blocks.py", line 81, in visit_hcb_html
    code_block = self.body[-1]
AttributeError: 'TextTranslator' object has no attribute 'body'
```

Any idea how to fix this?

**Comment by scopatz** [comment]
Thanks for reporting @ArtFlag. I am not sure how to fix this, but PRs are welcome!
